c:
	gcc -O3 -std=c89 -Wpedantic -Wall -Wextra -o sudoku sudoku.c
	./sudoku

c-optimized:
	gcc -funroll-loops -O3 -std=c89 -Wpedantic -Wall -Wextra -o sudoku sudoku_optimized.c

c-fast:
	gcc -funroll-loops -O3 -std=c89 -Wpedantic -Wall -Wextra -o sudoku sudoku_fast.c
